version: '3.1'

services:
  mariadb:
    image: mariadb:10.7.8
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    volumes:
      - ~/mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOSTS=mariadb

  api:
    image: api-nest
    build: ./api
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASS=root
      - DB_DATABASE=chamada
      - DB_SYNC=true
      - AUTH_SECRET=paos745dfbpq9w7hr4lfai7db4

  front:
    image: front-vite
    build: ./front
    ports:
      - 5173:5173
    environment:
      - BASE_URL="http://api:3000"
      - BASE_WSS="ws://api:3000"

